app:
  telegram-token: 7307114217:AAFZmhqRtB49FQroAzV02gTh9rt6OQQDUfE

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    enabled: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

default_bot_scrapper: "https://localhost:8081/"